name: Build & Publish
run-name: Version ${{github.ref_name}}
on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7
    - name: Build .xpi file
      run: |
        zip -r Quicktext@SONN.xpi * -x "*.git*"
    - uses: actions/upload-artifact@v7
      with:
        name: xpi
        path: Quicktext@SONN.xpi
  create-release:
    name: Create GitHub Release
    needs: build-linux
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: xpi
          path: xpi
      - uses: ncipollo/release-action@v1
        with:
          draft: false
          artifacts: "xpi/Quicktext@SONN.xpi"
          token: ${{secrets.GITHUB_TOKEN}}
          makeLatest: true
